### ISSUE TITLE
I can't find the format file `platex.fmt'! make: *** [Makefile:37: rireki.dvi] Error 1

### ISSUE THREAD

**Issue by eizanprime** [y-yu/rireki-tex#1]
I use archlinux with latex installed, 

for some reason, all attemps to compile the template fail, here is the output I get when running your makefile

platex rireki
This is e-pTeX, Version 3.14159265-p3.7.1-161114-2.6 (utf8.euc) (TeX Live 2017/Arch Linux) (preloaded format=platex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt platex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt:   /etc/texmf/web2c/fmtutil.cnf
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /home/eizanprime/.texlive/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /home/eizanprime/.texlive/texmf-var/web2c
mktexfmt [INFO]: did not find entry for byfmt=platex, skipped
mktexfmt [INFO]: Disabled formats: 6
mktexfmt [INFO]: Not selected formats: 36
mktexfmt [INFO]: Total formats: 42
mktexfmt [INFO]: exiting with status 0
I can't find the format file `platex.fmt'!
make: *** [Makefile:37: rireki.dvi] Error 1

**Comment by y-yu** [comment]
@eizanprime 

Hi.
`platex` is a LaTeX compiler for Japanese documents. You have to install `texlive-langcjk` which is LaTeX tool-sets for Japanese. Please execute following commands before `make`.

```console
$ yaourt texlive-langcjk
$ sudo mktexlsr
```

**Comment by eizanprime** [comment]
Looks like I was lacking the textlive-langjapanese package. Thank you very much !
